# Семинар по библиотеке Numpy

- про Jupyter Notebook: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/
- документация numpy: http://www.numpy.org/

Библиотека `numpy` является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [1]:
import numpy as np

In [2]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [5]:
vec.dtype

dtype('int64')

In [6]:
type(vec)

numpy.ndarray

Размер массива:

In [7]:
vec.shape

(3, 2)

Число осей:

In [8]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [9]:
np.sum(vec)

21

In [10]:
np.sum(vec, axis=0)

array([ 9, 12])

In [11]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [14]:
vec.sum(axis=0)

array([ 9, 12])

Транспонируем массив:

in-place

In [15]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [17]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [30]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [31]:
vec.reshape(1, 6)

array([[1, 2, 3, 4, 5, 6]])

In [32]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

Индексирование:

In [35]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
vec[:, 1]

array([2, 4, 6])

In [36]:
vec[2, :]

array([5, 6])

In [37]:
vec[1:2, 0]

array([3])

In [38]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

In [42]:
vec % 2 == 0

array([[False,  True],
       [False,  True],
       [False,  True]])

In [39]:
vec[vec % 2 == 0]

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [49]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [50]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [51]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [52]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [54]:
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

И, наконец - арифметические операции!

In [55]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [56]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [57]:
vec ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [58]:
vec + vec ** 2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [59]:
vec * vec ** 2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [64]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:
A B = C
Число столбцов в матрице А такое же как строк в матрице B.


In [71]:
2 * 10

20

In [68]:
# vec: [3, 2]; vec.T: [2, 3]
vec.dot(vec.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [73]:
vec.dot((vec ** 2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [74]:
vec @ (vec ** 2).T

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [75]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [82]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [78]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [79]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Генерация случайных чисел:

In [99]:
np.random.rand(2, 3)

array([[0.9326728 , 0.73746012, 0.3515612 ],
       [0.47832321, 0.11952423, 0.03098871]])

In [96]:
np.random.seed(238734)
np.random.rand(2, 3)

array([[0.18461939, 0.32038548, 0.39922984],
       [0.93600531, 0.18027964, 0.42197632]])

In [100]:
np.random.randn(3, 2)

array([[ 0.47989913,  0.6017447 ],
       [ 0.81792966,  0.18068111],
       [-1.05644345, -1.69986019]])

In [108]:
np.random.normal(2, 1, size=3)

array([2.19132676, 2.88673828, 2.63272436])

In [112]:
np.random.randint(5, 10, size=3)

array([7, 9, 7])

Почему вообще используют `numpy`?

In [105]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [106]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

CPU times: user 21.3 s, sys: 62.7 ms, total: 21.4 s
Wall time: 21.4 s


In [107]:
%%time
C = A @ B

CPU times: user 7.29 ms, sys: 17.9 ms, total: 25.2 ms
Wall time: 2.48 ms


### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [ ]:
# ┌(▼▼メ)┘ └(メ▼▼)┐